# Generated by Django 2.1.5 on 2019-01-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilities',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipes',
            name='utilities',
            field=models.ManyToManyField(to='recipes.Utilities'),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='utilityPic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
