# Generated by Django 2.1.5 on 2019-01-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20190107_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='utilities',
            field=models.ManyToManyField(null=True, to='recipes.Utilities'),
        ),
    ]
