# Generated by Django 2.1.5 on 2019-01-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20190107_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='utilities',
            field=models.ManyToManyField(blank=True, to='recipes.Utilities'),
        ),
    ]
