# Generated by Django 2.1.5 on 2019-01-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20190107_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilities',
            name='utilityPic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
