# Generated by Django 2.1.5 on 2019-01-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labels',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipes',
            name='cKal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipes',
            name='forPeople',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='recipes',
            name='labels',
            field=models.ManyToManyField(to='recipes.Labels'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='timeToMake',
            field=models.IntegerField(blank=True, default=20),
            preserve_default=False,
        ),
    ]
