# Generated by Django 2.1.5 on 2019-01-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20190107_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='timeToMake',
            field=models.IntegerField(blank=True, default=20),
        ),
    ]
