# Generated by Django 2.1.5 on 2019-01-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20190107_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='separator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipes',
            name='timeToMakeActive',
            field=models.IntegerField(blank=True, default=20),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='health',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='steps',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='stepNr',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
