# Generated by Django 2.1.5 on 2019-01-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20190108_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='steps',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='steps',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
