# Generated by Django 2.1.5 on 2019-01-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20190108_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsamount',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
