# Generated by Django 2.1.5 on 2019-01-09 09:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20190108_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsamount',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientsamount',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.Unit'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
