# Generated by Django 2.1.5 on 2019-01-11 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20190109_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsamount',
            name='recipes',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.Recipes'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.Recipes'),
        ),
    ]
