# Generated by Django 2.1.5 on 2019-01-14 11:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_auto_20190111_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
