# Generated by Django 2.1.5 on 2019-01-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20190114_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsamount',
            name='processed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
