# Generated by Django 2.1.5 on 2019-01-15 10:11

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_auto_20190114_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.Labels'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True),
        ),
    ]
